version: '3.0'

#Containers by Docker Compose 

services:
  # MariaDb Container with service 
  mariadb:
    #Dockerfile location from current docker-compose.yml
    build: ./requirements/mariadb 
    #Same name for service and container 
    container_name: mariadb
    # Environment Variables
    environment:
      - INSTALL=${INSTALL}
      - MARIADB_HOST_NAME=${MARIADB_HOST_NAME}
      - MARIADB_HOST_V4=${MARIADB_HOST_V4}
      - MARIADB_HOST_V6=${MARIADB_HOST_V6}
      - MARIADB_DB=${MARIADB_DB}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PWD=${MARIADB_PWD}
      - MARIADB_ADMIN_USER=${MARIADB_ADMIN_USER}
      - MARIADB_ADMIN_PWD=${MARIADB_ADMIN_PWD}
    
    image:  mariadb
    #Network from generated 
    networks: 
      - inception
    #Restart policy 
    restart: always
    #Volume to be Independent of Container 
    volumes: 
      - volume-mariadb:/var/lib/mysql
  
  # Nginx container with service 
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on: 
      - wordpress
    image: nginx
    networks: 
      - inception
    ports: 
      - 443:443 
    restart: always
    volumes:
      - volume-wordpress:/var/www/wordpress
  
  # Wordpress container with service
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    image: wordpress
    networks:
      - inception
    restart: always
    volumes:
      - volume-wordpress:/var/www/wordpress
    
  # Netword Bridge
  networks:
    
    inception:
      driver: bridge

  # Volumes from Host Mounted Directory for Serviced Containers 
  volumes:
    # mariadb volume
    volume-mariadb:
      # Driver selection among Local, Volume ( docker volume ) , Temporary File System (tmpfs)
      driver: local
      # Driver options 
      driver_opts: 
        # Bind Path
        device: ~/${USER}/data/mariadb
        # Mount Option (Regerence from Mount Command Manual)
        o: "bind"
        # No Fs Type due to binding option
        type: none

    # Volume for Wordpress
    volume-wordpress: 
      driver: local
      driver_opts: 
        device: ~/${USER}/data/wordpress
        o: "bind"
        type: none